#!/bin/sh
#
# Psuedo-backend for CUPS testing purposes.
#
# Copyright © 2020-2024 by OpenPrinting.
# Copyright © 2011 by Apple Inc.
#
# Licensed under Apache License v2.0.  See the file "LICENSE" for more
# information.
#

if test $# = 0; then
	echo 'direct pseudo:///deskjet "HP DeskJet" "HP DeskJet (pseudo)" "MFG:HP;MDL:DeskJet;CMD:PCL;" "Nowhere"'
	echo 'direct pseudo:///laserjet "HP LaserJet" "HP LaserJet (pseudo)" "MFG:HP;MDL:LaserJet;CMD:PCL;" "Nowhere"'
	exit 0
fi

cat $6 >/dev/null
sleep 5
exit 0
