#! /bin/sh
#
# Script to reload the CUPS daemon (cupsd).
#
# Copyright © 2020 by Till Kamppeter
#
# Licensed under Apache License v2.0.  See the file "LICENSE" for more
# information.
#
set -e -x

# Send HUP signal to CUPS
echo "==> Sending HUP to CUPS"
PID=$(cat "${SNAP_COMMON}/pid/cupsd.pid" || true)
if [ -n "${PID}" ] && kill -0 "${PID}" 2>/dev/null; then
    kill -HUP "${PID}"
else
    echo "==> No CUPS process found"
fi
