name: Push new tag update to stable branch

on:
  schedule:
    - cron: '9 7 * * *'
  workflow_dispatch:
    inputs:
      workflow_choice:
        description: "Choose YAML to update"
        required: true
        default: "both"
        type: choice
        options:
          - snapcraft
          - rockcraft
          - both

jobs:
  update-yamls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Run desktop-snaps action (Snapcraft)
        if: ${{ github.event_name == 'schedule' || github.event.inputs.workflow_choice == 'snapcraft' || github.event.inputs.workflow_choice == 'both' }}
        uses: ubuntu/desktop-snaps@stable
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.repository }}
          version-schema: 'v(\d+\.\d+\.\d+)'
          yaml-path: 'packages/snapcraft.yaml'
          readme-path: packages/README.md

      - name: Run desktop-snaps action (Rockcraft)
        if: ${{ github.event_name == 'schedule' || github.event.inputs.workflow_choice == 'rockcraft' || github.event.inputs.workflow_choice == 'both' }}
        uses: ubuntu/desktop-snaps@stable
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.repository }}
          rock-version-schema: 'v(\d+\.\d+\.\d+)'
          yaml-path: 'packages/rockcraft.yaml'